config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users
  resources :questions, except: [:show, :new, :index]
  resource :session, only: [:new, :create, :destroy]
  resources :hashtags, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  has_and_belongs_to_many :questions
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true
  has_and_belongs_to_many :hashtags

  validates :text, presence: true
  validates :text, length: { maximum: 255 }

  before_save do
    self.hashtags.clear
    fields_scan
  end

  def fields_scan
    string = self.text + " " + self.answer.to_s
    tags = string.scan(/#+[[[:word:]]-]+/)
    tags.uniq.map do |tag|
      hashtag = Hashtag.find_or_create_by(name: tag.downcase.delete('#'))
      self.hashtags << hashtag
    end
  end
end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord
  ITERATIONS = 20_000
  DIGEST = OpenSSL::Digest::SHA256.new

  has_many :questions

  validates :email, :username, presence: true
  validates :email, :username, uniqueness: true
  validates :email, format: { with: /\A[\w\d]+[\w\d.]+@[\w\d]+\.[\w]+/ }
  validates :username, length: { maximum: 40 }
  validates :username, format: { with: /\A[\w]+\z/ }
  validates :user_background, format: { with: /\A#+[a-zA-Z\d]+\z/}, length: { is: 7 }, allow_blank: true
  validates :avatar_url, format: { with: /https?:\/\/[\S]+/}, allow_blank: true

  attr_accessor :password

  validates_presence_of :password, on: :create
  validates_confirmation_of :password

  before_save :encrypt_password
  before_validation :user_downcase

  def user_downcase
    username.downcase!
  end

  def encrypt_password
    if password.present?
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))
      self.password_hash = User.hash_to_string(
        OpenSSL::PKCS5.pbkdf2_hmac(
          password, password_salt, ITERATIONS, DIGEST.length, DIGEST
        )
      )
    end
  end

  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  def self.authenticate(email, password)
    user = find_by(email: email)
    return nil unless user.present?

    hashed_password = User.hash_to_string(
      OpenSSL::PKCS5.pbkdf2_hmac(
        password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST
      )
    )

    return user if user.password_hash == hashed_password

    nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def reject_user
    redirect_to root_path, alert: 'Вам сюда нельзя!'
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  before_action :set_hashtag, only: [:show]

  def show
    @questions = @hashtag.questions
  end

  private

  def set_hashtag
    @hashtag = Hashtag.find_by(name: params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: [:show, :edit, :update, :destroy]

  before_action :authorize_user, except: [:create]

  def edit
  end

  def create
    @question = Question.new(question_params)

    @question.author = @current_user

    if check_captcha(@question) && @question.save
      redirect_to user_path(@question.user), notice: 'Вопрос задан'
    else
      render :edit
    end
  end

  def update
    if @question.update(question_params)
      redirect_to user_path(@question.user), notice: 'Вопрос сохранен'
    else
      render :edit
    end
  end

  def destroy
    user = @question.user
    @question.destroy
    redirect_to user_path(user), notice: 'Вопрос удален'
  end

  private

  def authorize_user
    reject_user unless @question.user == current_user
  end

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    if current_user.present? &&
      params[:question][:user_id].to_i == current_user.id
      params.require(:question).permit(:user_id, :text, :answer)
    else
      @question.answer = nil if @question
      params.require(:question).permit(:user_id, :text)
    end
  end

  def check_captcha(model)
    current_user.present? || verify_recaptcha(model: model)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])

    if user.present?
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Вы успешно залогинились'
    else
      flash.now.alert = 'Неправильный имейл или пароль'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Вы разлогинились! Приходите еще!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: [:index, :create, :new]

  before_action :authorize_user, except: [:index, :new, :create, :show]

  def index
    @users = User.all
  end

  def new
    redirect_to root_url, alert: 'Вы уже залогинены' if current_user.present?

    @user = User.new
  end

  def create
    redirect_to root_url, alert: 'Вы уже залогинены' if current_user.present?

    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Вы успешно зарегистрировались!'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Данные обновлены'
    else
      render 'edit'
    end
  end

  def show
    @questions = @user.questions.order(created_at: :desc)

    @new_question = @user.questions.build

    @questions_count = @questions.count
    @answers_count = @questions.where.not(answer: nil).count
    @unanswered_count = @questions_count - @answers_count
  end

  def destroy
    if current_user == @user
      current_user.destroy
      redirect_to root_url, notice: 'Вы успешно удалили свой аккаунт'
    else
      redirect_to root_url
    end
  end

  private

  def authorize_user
    reject_user unless @user == current_user
  end

  def load_user
    @user ||= User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :name, :username, :avatar_url, :user_background)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sklonenie(number, krokodil, krokodila, krokodilov)
    ostatok = number % 10
    ostatok_big = number % 100

    if ostatok_big.between?(10,14) || ostatok.between?(5,9) || ostatok == 0
      krokodilov
    elsif ostatok == 1
      krokodil
    else
      krokodila
    end
  end

  def fa_icon(icon_class)
    content_tag 'span', '', class: "fa fa-#{icon_class}"
  end
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
  def all_hashtags
    Hashtag.all.order(updated_at: :desc)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_avatar(user)
    if user.avatar_url.present?
      user.avatar_url
    else
      asset_path 'avatar.jpg'
    end
  end

  def color_list
    colors = {
      "Стандартный" => "#2e2f41",
      "OrangeRed" => "#CD4929",
      "Aqua" => "#00C6C1",
      "PaleVioletRed" => "#A15C73",
      "Navy" => "#383C57",
      "Crimson" => "#DC143C",
      "DarkCyan" => "#008B8B"
    }
    colors.each_key { |color| color }
  end
end

app/views/hashtags/show.html.erb
<div class="content-wrapper buffer-both">
  <div class="text-lead">
    Вот все вопросы с этим хештегом
  </div>

  <div class="user-questions buffer-both">
    <div class="questions-list">
      <% @questions.each do |question| %>
        <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <title>Хорошие вопросы</title>
  <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <script src="//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="header">
  <div class="container">
    <div class="header-logo">
      <h1 class="header-title"><%= link_to "Хорошие вопросы", root_path %></h1>
    </div>

    <div class="header-nav">
      <% if current_user %>
        <%= link_to "@#{current_user.username}", user_path(current_user) %> |
        <%= link_to 'Выйти', session_path, data: { method: :delete } %>
      <% else %>
        <%= link_to 'Зарегистрироваться', new_user_path,
                    class: 'button button-light button-small' %>
        <%= link_to 'Войти', new_session_path,
                    class: 'button button-light button-small' %>
      <% end %>
    </div>
  </div>
</div>

<div class="content">
  <div class="container">
    <% if flash.any? %>
      <div class="content-wrapper buffer-both">
        <% flash.each do |name, message| %>
          <%= content_tag :div, message, class: "flash-#{name}" %>
        <% end %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/questions/_form.html.erb
<div class="form">
  <%= form_for(@question) do |f| %>
    <% if @question.errors.any? %>
      <div class="form-errors">
        <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li class="form-error-message"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.hidden_field :user_id %>

    <div class="form-field">
      <%= f.label :text, 'Вопрос', class: 'form-label' %>
      <%= f.text_area :text, class: 'form-textarea' %>
    </div>

    <% if current_user.present? && current_user == @question.user %>
      <div class="form-field">
        <%= f.label :answer, 'Ответ', class: 'form-label' %>
        <%= f.text_area :answer, class: 'form-textarea' %>
      </div>
    <% end %>

    <%= recaptcha_tags unless current_user.present? %>

    <div class="form-action buffer-both">
      <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      или
      <%= link_to "вернуться", user_path(@question.user) %>
    </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<div class="question">
  <div class="question-content">

    <div class="question-text text-lead">
      <%= question.text %>
    </div>

    <% if question.author.present? %>
      <div class="question-text text-medium less-margin-top">
        <%= link_to "- @#{question.author.username}", user_path(question.author) if question.author %>
      </div>
    <% end %>

    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= question.answer %>
      </div>
    <% end %>

    <div class="question-date">
      <%= l(question.created_at, format: :short) %>
    </div>
  </div>

  <div class="text-medium margin-left-15 less-margin-top">
    <% question.hashtags.uniq.map do |hashtag| %>
      <%= link_to "##{hashtag.name}", hashtag_path(hashtag.name) %>
    <% end %>
  </div>

  <% if question.user == current_user %>
    <% edit_icon = question.answer.blank? ? 'reply' : 'pencil' %>

    <div class="question-actions">
      <%= link_to fa_icon(edit_icon), edit_question_path(question) %>
      <%= link_to fa_icon('trash-o'), question_path(question),
                  method: :delete, data: { confirm: 'Точно удалить вопрос?' } %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Вопрос</h1>

  <div class="column-1-2">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Править профиль</h1>

  <div class="column-1-2">
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-field">
        <%= f.label 'Выбрать цвет фона', class: 'form-label' %>
        <%= f.select :user_background, color_list, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :username, class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'Ваше имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'URL вашей аватарки', class: 'form-label' %>
        <%= f.text_field :avatar_url, class: 'form-text-field' %>
      </div>

      <div class="buffer-top-large buffer-bottom">
        Если не хотите менять пароль — оставьте эти поля пустыми!
      </div>

      <div class="form-field">
        <%= f.label :password, class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action buffer-top">
        <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      </div>
    <% end %>

    <div class="buffer-both">
      <%= link_to "Удалить аккаунт", @user, method: :delete,
                  data: { confirm: "Вы уверены, что хотите удалить аккаунт?" } %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Наши пользователи</h1>
  </div>

  <% @users.each do |user| %>
    <div class="users-list-item">
      <div class="user-image-div user-image-div-small">
        <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
      </div>
    </div>
  <% end %>
</div>

<div class="content-wrapper buffer-both text-center">
  <div class="text-medium">
    <% all_hashtags.each do |hashtag| %>
      <%= link_to "##{hashtag.name}", hashtag_path(hashtag.name) if hashtag.questions.present? %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Присоединяйся к нам!</h1>

  <div class="column-1-2">
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-field">
        <%= f.label :email, 'Логин (email)', class: 'form-label' %>
        <%= f.text_field :email, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :username, 'Никнейм', class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :name, 'Имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password, 'Пароль', class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, 'Пароль ещё раз', class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action">
        <%= f.submit 'Зарегистрироваться', class: 'button button-small button-dark' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= content_tag :div, class: ["user-header", "text-center"], style: ["background: #{@user.user_background}"] do %>
<h1 class="title-medium">
    <%= @user.name %>
  </h1>

  <div class="buffer-both">
    <%= link_to 'Редактировать профиль', edit_user_path(@user) if current_user == @user %>
  </div>

  <div class="user-image-div">
    <%= image_tag user_avatar(@user), class: 'user-image', alt: '[Фото]' %>
  </div>

  <h2 class="title-small buffer-both">
    @<%= @user.username %>
  </h2>
<% end %>

<div class="user-details">
  <div class="user-ask-button container text-center">
    <%= link_to "Спроси меня", '', class: 'button button-light', id: 'ask-button' %>
  </div>

  <div class="user-statistics container text-center">
    <div class="column-1-3">
      <h1 class="title-small"><%= "#{@questions_count}" %></h1>
      <p><%= "#{sklonenie(@questions_count, "вопрос", "вопроса", "вопросов")}" %></p>
    </div>
    <div class="column-1-3">
      <h1 class="title-small"><%= "#{@answers_count}" %></h1>
      <p><%= "#{sklonenie(@answers_count, "ответ", "ответа", "ответов")}" %></p>
    </div>
    <div class="column-1-3">
      <h1 class="title-small"><%= "#{@unanswered_count}" %></h1>
      <p>без ответа</p>
    </div>
  </div>
</div>

<div class="user-question-form-div column-1-4 column-1-4-right" id='ask-form'>
  <div class="user-question-form buffer-both">
    <%= form_for @new_question do |f| %>
      <%= f.hidden_field :user_id %>

      <div class="form-field">
        <%= f.label "Ваш вопрос для @#{@user.username}", class: 'form-label' %>
        <%= f.text_area :text, class: 'form-textarea' %>
      </div>

      <%= recaptcha_tags size: 'compact' unless current_user.present? %>

      <div class="form-action">
        <%= submit_tag 'Задать вопрос', class: 'button button-small button-dark' %>
      </div>
    <% end %>
  </div>
</div>

<div class="column-3-4">
  <div class="user-questions buffer-both">
    <div class="questions-list">
      <% @questions.each do |question| %>
        <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>